### ISSUE TITLE
ONNX simplify error occurs when either width or height is not a multiple of 7

### ISSUE THREAD

**Issue by chohk88** [NVlabs/FasterViT#106]
I'm using the provided [onnx_convert.py](https://github.com/NVlabs/FasterViT/blob/main/onnx_convert.py) function to export the faster_vit_0_any_res model, which accepts input images of size 800x1536, into the ONNX format. 

However, I've encountered an issue when attempting to simplify the ONNX model (I included the ONNX simplify process). This problem arises when either the width or height of the image isn't divisible by 7. The error message is as follows:

```less
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Slice, node name: /levels.2/blocks.0/Slice): [ShapeInferenceError] Inferred shape and existing shape differ in rank: (3) vs (0)
```

```less
root@5820-Tower:/develop/FasterViT# python onnx_convert.py --model-name faster_vit_0_any_res --resolution-h 576 --resolution-w 960 --onnx-opset 17
/usr/local/lib/python3.8/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:3435.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/develop/FasterViT/fastervit/models/faster_vit_any_res.py:853: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if pad_r > 0 or pad_b > 0:
/develop/FasterViT/fastervit/models/faster_vit_any_res.py:352: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  seq_length = int(seq_length**0.5)
/develop/FasterViT/fastervit/models/faster_vit_any_res.py:280: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if n_global_feature > 0 and self.ct_correct:
/develop/FasterViT/fastervit/models/faster_vit_any_res.py:297: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if n_global_feature>0 and self.ct_correct:
/develop/FasterViT/fastervit/models/faster_vit_any_res.py:866: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if pad_r > 0 or pad_b > 0:
  if n_global_feature>0 and self.ct_correct:
========== Diagnostic Run torch.onnx.export version 1.14.0a0+44dac51 ===========
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Traceback (most recent call last):
  File "onnx_convert.py", line 129, in <module>
    main()
  File "onnx_convert.py", line 53, in main
    export_onnx(model,
  File "onnx_convert.py", line 107, in export_onnx
    model_simp, check = simplify(onnx_model)
  File "/usr/local/lib/python3.8/dist-packages/onnxsim/onnx_simplifier.py", line 197, in simplify
    model_opt_bytes = C.simplify(
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Slice, node name: /levels.2/blocks.0/Slice): [ShapeInferenceError] Inferred shape and existing shape differ in rank: (3) vs (0)
```

For instance, the following commands work as expected:
```sh
python onnx_convert.py --model-name faster_vit_0_any_res --resolution-h 224 --resolution-w 672 --onnx-opset 17
```
or
```sh
python onnx_convert.py --model-name faster_vit_0_any_res --resolution-h 896 --resolution-w 896 --onnx-opset 17
```
However, I encounter the error when I run:
```sh
python onnx_convert.py --model-name faster_vit_0_any_res --resolution-h 224 --resolution-w 256 --onnx-opset 17
```
or
```sh
python onnx_convert.py --model-name faster_vit_0_any_res --resolution-h 800 --resolution-w 800 --onnx-opset 17
```
This error occurs during the ONNX simplification step.

I set the batch size to 1 (non-dynamic batch size) in torch.onnx.export and added ONNX simplification before shape inference, as shown in the code snippet below:

```python

from onnxsim import simplify

def export_onnx(
    model: torch.nn.Module,
    sample_inputs,
    export_params: bool = False,
    opset_version: int = 17,
    result_dir: str = "",
    batch_first: bool = True,
    is_training: bool = False,
    onnx_file_name: str ="",
):
    f = io.BytesIO()
    torch.onnx.export(
        model,
        # ONNX has issue to unpack the tuple of parameters to the model.
        # https://github.com/pytorch/pytorch/issues/11456
        (sample_inputs,) if type(sample_inputs) == tuple else sample_inputs,
        f,
        export_params=export_params,
        training=torch.onnx.TrainingMode.TRAINING
        if is_training
        else torch.onnx.TrainingMode.EVAL,
        do_constant_folding=True,
        opset_version=opset_version,
    )
    onnx_model = onnx.load_model_from_string(f.getvalue(), onnx.ModelProto)
    onnx.checker.check_model(onnx_model)

    model_simp, check = simplify(onnx_model)
    f.close()
    model_simp_shape = onnx.shape_inference.infer_shapes(model_simp)

    # Constant folding to simplify the ONNX
    graph = gs.import_onnx(model_simp_shape)
    graph.fold_constants().cleanup()

    onnx.save(
        gs.export_onnx(graph),
        os.path.join(
            result_dir, onnx_file_name
        ),
    )
    return model_simp_shape
```

I've been trying to solve this problem by examining the parts where [add padding ](https://github.com/NVlabs/FasterViT/blob/main/fastervit/models/faster_vit_any_res.py#L851) or [perform slicing](https://github.com/NVlabs/FasterViT/blob/main/fastervit/models/faster_vit_any_res.py#L701). Unfortunately, I haven't figured out the underlying reason behind it yet. Could you provide any help or insights?

**Comment by ahatamiz** [comment]
Hi @chohk88 please excuse me for a rather late reply on this issue. I have tried to reproduce the issue but was not successful. 

Specifically, I ran the following cases:

`python onnx_convert.py --resolution-h=800 --resolution-w=1536
`

or 

`python onnx_convert.py --resolution-h=576 --resolution-w=960
`

or even:

`python onnx_convert.py --resolution-h=224 --resolution-w=256
`
The model can be successfully converted in all cases and I get the following output (please ignore the foldable nodes warning)

```
================ Diagnostic Run torch.onnx.export version 2.0.0 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

2023-09-02 08:33:23.148199172 [W:onnxruntime:, unsqueeze_elimination.cc:20 Apply] UnsqueezeElimination cannot remove node /levels.2/Unsqueeze_17
2023-09-02 08:33:23.148223425 [W:onnxruntime:, unsqueeze_elimination.cc:20 Apply] UnsqueezeElimination cannot remove node /levels.2/Unsqueeze_16
2023-09-02 08:33:23.148276609 [W:onnxruntime:, unsqueeze_elimination.cc:20 Apply] UnsqueezeElimination cannot remove node /levels.2/global_tokenizer/Unsqueeze_5
2023-09-02 08:33:23.148285145 [W:onnxruntime:, unsqueeze_elimination.cc:20 Apply] UnsqueezeElimination cannot remove node /levels.2/global_tokenizer/Unsqueeze_1
[W] colored module is not installed, will not use colors when logging. To enable colors, please install the colored module: python3 -m pip install colored
[W] It looks like this model contains foldable nodes that produce large outputs.
In order to avoid bloating the model, you may want to set a constant-folding size threshold.
Note: Large tensors and their corresponding sizes were: {'onnx::Gather_4342': '1 MiB', 'onnx::Gather_4298': '1 MiB', 'onnx::Gather_4254': '1 MiB', 'onnx::Gather_4210': '1 MiB', 'onnx::Gather_4166': '1 MiB', '/levels.2/blocks.0/hat_attn/pos_emb_funct/cpb_mlp/cpb_mlp.0/MatMul_output_0': '3 MiB', '/levels.2/blocks.0/hat_attn/pos_emb_funct/cpb_mlp/cpb_mlp.0/Add_output_0': '3 MiB', '/levels.2/blocks.0/hat_attn/pos_emb_funct/cpb_mlp/cpb_mlp.1/Relu_output_0': '3 MiB', '/levels.2/blocks.0/hat_attn/pos_emb_funct/Gather_output_0': '5 MiB', '/levels.2/blocks.0/hat_attn/pos_emb_funct/Reshape_1_output_0': '5 MiB', '/levels.2/blocks.0/hat_attn/pos_emb_funct/Transpose_output_0': '5 MiB', '/levels.2/blocks.0/hat_attn/pos_emb_funct/Sigmoid_output_0': '5 MiB', '/levels.2/blocks.0/hat_attn/pos_emb_funct/Mul_output_0': '5 MiB', '/levels.2/blocks.1/hat_attn/pos_emb_funct/cpb_mlp/cpb_mlp.0/MatMul_output_0': '3 MiB', '/levels.2/blocks.1/hat_attn/pos_emb_funct/cpb_mlp/cpb_mlp.0/Add_output_0': '3 MiB', '/levels.2/blocks.1/hat_attn/pos_emb_funct/cpb_mlp/cpb_mlp.1/Relu_output_0': '3 MiB', '/levels.2/blocks.1/hat_attn/pos_emb_funct/Gather_output_0': '5 MiB', '/levels.2/blocks.1/hat_attn/pos_emb_funct/Reshape_1_output_0': '5 MiB', '/levels.2/blocks.1/hat_attn/pos_emb_funct/Transpose_output_0': '5 MiB', '/levels.2/blocks.1/hat_attn/pos_emb_funct/Sigmoid_output_0': '5 MiB', '/levels.2/blocks.1/hat_attn/pos_emb_funct/Mul_output_0': '5 MiB', '/levels.2/blocks.2/hat_attn/pos_emb_funct/cpb_mlp/cpb_mlp.0/MatMul_output_0': '3 MiB', '/levels.2/blocks.2/hat_attn/pos_emb_funct/cpb_mlp/cpb_mlp.0/Add_output_0': '3 MiB', '/levels.2/blocks.2/hat_attn/pos_emb_funct/cpb_mlp/cpb_mlp.1/Relu_output_0': '3 MiB', '/levels.2/blocks.2/hat_attn/pos_emb_funct/Gather_output_0': '5 MiB', '/levels.2/blocks.2/hat_attn/pos_emb_funct/Reshape_1_output_0': '5 MiB', '/levels.2/blocks.2/hat_attn/pos_emb_funct/Transpose_output_0': '5 MiB', '/levels.2/blocks.2/hat_attn/pos_emb_funct/Sigmoid_output_0': '5 MiB', '/levels.2/blocks.2/hat_attn/pos_emb_funct/Mul_output_0': '5 MiB', '/levels.2/blocks.3/hat_attn/pos_emb_funct/cpb_mlp/cpb_mlp.0/MatMul_output_0': '3 MiB', '/levels.2/blocks.3/hat_attn/pos_emb_funct/cpb_mlp/cpb_mlp.0/Add_output_0': '3 MiB', '/levels.2/blocks.3/hat_attn/pos_emb_funct/cpb_mlp/cpb_mlp.1/Relu_output_0': '3 MiB', '/levels.2/blocks.3/hat_attn/pos_emb_funct/Gather_output_0': '5 MiB', '/levels.2/blocks.3/hat_attn/pos_emb_funct/Reshape_1_output_0': '5 MiB', '/levels.2/blocks.3/hat_attn/pos_emb_funct/Transpose_output_0': '5 MiB', '/levels.2/blocks.3/hat_attn/pos_emb_funct/Sigmoid_output_0': '5 MiB', '/levels.2/blocks.3/hat_attn/pos_emb_funct/Mul_output_0': '5 MiB', '/levels.2/blocks.4/hat_attn/pos_emb_funct/cpb_mlp/cpb_mlp.0/MatMul_output_0': '3 MiB', '/levels.2/blocks.4/hat_attn/pos_emb_funct/cpb_mlp/cpb_mlp.0/Add_output_0': '3 MiB', '/levels.2/blocks.4/hat_attn/pos_emb_funct/cpb_mlp/cpb_mlp.1/Relu_output_0': '3 MiB', '/levels.2/blocks.4/hat_attn/pos_emb_funct/Gather_output_0': '5 MiB', '/levels.2/blocks.4/hat_attn/pos_emb_funct/Reshape_1_output_0': '5 MiB', '/levels.2/blocks.4/hat_attn/pos_emb_funct/Transpose_output_0': '5 MiB', '/levels.2/blocks.4/hat_attn/pos_emb_funct/Sigmoid_output_0': '5 MiB', '/levels.2/blocks.4/hat_attn/pos_emb_funct/Mul_output_0': '5 MiB', '/levels.2/blocks.5/hat_attn/pos_emb_funct/cpb_mlp/cpb_mlp.0/MatMul_output_0': '3 MiB', '/levels.2/blocks.5/hat_attn/pos_emb_funct/cpb_mlp/cpb_mlp.0/Add_output_0': '3 MiB', '/levels.2/blocks.5/hat_attn/pos_emb_funct/cpb_mlp/cpb_mlp.1/Relu_output_0': '3 MiB', '/levels.2/blocks.5/hat_attn/pos_emb_funct/Gather_output_0': '5 MiB', '/levels.2/blocks.5/hat_attn/pos_emb_funct/Reshape_1_output_0': '5 MiB', '/levels.2/blocks.5/hat_attn/pos_emb_funct/Transpose_output_0': '5 MiB', '/levels.2/blocks.5/hat_attn/pos_emb_funct/Sigmoid_output_0': '5 MiB', '/levels.2/blocks.5/hat_attn/pos_emb_funct/Mul_output_0': '5 MiB'}
```

I believe it could be due to discrepancies in the version of installed packages, specifically onnx and onnx_graphsurgeon. Specifically, the following works for me with a latest version of the code from the main branch:

```
onnx==1.14.1
onnx_graphsurgeon==0.3.27
onnxruntime==1.15.1
timm==0.9.6
torch==2.0.0
```

I appreciate if you could update the package dependencies to the above with the latest model on the main branch and let me know if the issue still exists. 

Thanks again!
