### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by 18370636086** [NVlabs/FasterViT#50]
when run 'from fastervit import create_model', it got wrong with follows, how to solve it ? Thank you very much!
Traceback (most recent call last):
  File "/remote-home/cs_cs_lhy/code/kaggle/bm/breast_cancer_classification_benign_malignantgai.py", line 29, in <module>
    from fastervit import create_model
  File "/root/anaconda3/envs/kbm/lib/python3.10/site-packages/fastervit/__init__.py", line 1, in <module>
    from .models.registry import create_model
  File "/root/anaconda3/envs/kbm/lib/python3.10/site-packages/fastervit/models/__init__.py", line 2, in <module>
    from .faster_vit_any_res import *
  File "/root/anaconda3/envs/kbm/lib/python3.10/site-packages/fastervit/models/faster_vit_any_res.py", line 17, in <module>
    from utils.checkpoint import load_checkpoint
ModuleNotFoundError: No module named 'utils'

**Comment by ahatamiz** [comment]
Hi @18370636086 , thanks for the note. Please see the latest release which should address this issue.
